name: CI Test

on: ['pull_request']
jobs:
  prepare:
    runs-on: ubuntu-latest
    name: setup verdaccio
    services:
      verdaccio:
        image: verdaccio/verdaccio:nightly-master
        ports:
          - 4873:4873
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Use Node 14
      uses: actions/setup-node@v1
      with:
        node-version: 14 
   