name: CI Test

on: ['pull_request']
jobs:
  prepare:
    runs-on: ubuntu-latest
    name: ci
    services:
      verdaccio:
        image: verdaccio/verdaccio:5
        ports:
          - 4873:4873
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Use Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install
      run: npm install --registry http://localhost:4873 --loglevel verbose
    - name: Test
      run: npm test
    - name: credentials
      run: npm run login
    - name: Publishing
      run: npm publish --registry http://localhost:4873
    - name: install global cli
      run: npm i -g install docker-integration-test --registry http://localhost:4873 
    - name: run cli
      run: echo '::set-output name=CLI::$(super-cli)'
      id: cli-output
    - name: validate
      run: ${{ steps.cli-output.outputs.CLI == 'here this is my CLI' }} 
   