name: CI Test

on: ['pull_request']
jobs:
  prepare:
    runs-on: ubuntu-latest
    name: setup verdaccio
    services:
      verdaccio:
        image: verdaccio/verdaccio:nightly-master
        ports:
          - 4873:4873
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Use Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install
      run: npm install
    - name: Test
      run: npm test

   