name: CI Test

on: ['pull_request']
jobs:  
  prepare:
    runs-on: ubuntu-latest
    name: ci
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Use Node
      uses: actions/setup-node@v2
      with:
        node-version: 16   
  